export const ITEMS = [
  'accordion',
  'alert-dialog',
  'alert',
  'aspect-ratio',
  'badge',
  'checkbox',
  'collapsible',
  'context-menu',
  'dialog',
  'dropdown-menu',
  'hover-card',
  'input',
  'popover',
  'typography',
] as const;
