export const COMPONENTS = [
  { slug: 'accordion', name: 'Accordion' },
  { slug: 'alert', name: 'Alert' },
  { slug: 'alert-dialog', name: 'Alert Dialog' },
  { slug: 'aspect-ratio', name: 'Aspect Ratio' },
  { slug: 'avatar', name: 'Avatar' },
  { slug: 'badge', name: 'Badge' },
  { slug: 'button', name: 'Button' },
  { slug: 'card', name: 'Card' },
  { slug: 'checkbox', name: 'Checkbox' },
  { slug: 'collapsible', name: 'Collapsible' },
  { slug: 'context-menu', name: 'Context Menu' },
  { slug: 'dialog', name: 'Dialog' },
  { slug: 'dropdown-menu', name: 'Dropdown Menu' },
  { slug: 'hover-card', name: 'Hover Card' },
  { slug: 'input', name: 'Input' },
  { slug: 'label', name: 'Label' },
  { slug: 'menubar', name: 'Menubar' },
  { slug: 'popover', name: 'Popover' },
  { slug: 'progress', name: 'Progress' },
  { slug: 'radio-group', name: 'Radio Group' },
  { slug: 'select', name: 'Select' },
  { slug: 'separator', name: 'Separator' },
  { slug: 'skeleton', name: 'Skeleton' },
  { slug: 'switch', name: 'Switch' },
  { slug: 'tabs', name: 'Tabs' },
  { slug: 'text', name: 'Text' },
  { slug: 'textarea', name: 'Textarea' },
  { slug: 'toggle', name: 'Toggle' },
  { slug: 'toggle-group', name: 'Toggle Group' },
  { slug: 'tooltip', name: 'Tooltip' },
] as const;
