import {
  AlertCircleIcon,
  ListCollapseIcon,
  AlertTriangleIcon,
  InspectionPanelIcon,
  CircleUserRoundIcon,
  BadgeIcon,
  RectangleHorizontalIcon,
  IdCardIcon,
  SquareCheckBigIcon,
  FoldVerticalIcon,
  PictureInPicture2Icon,
  CaptionsIcon,
  ChevronDownIcon,
  MousePointer2Icon,
  TagIcon,
  TextCursorInputIcon,
  MinusIcon,
  SquaresIntersectIcon,
  HourglassIcon,
  ListIcon,
  ListCheckIcon,
  Rows3Icon,
  BoneIcon,
  Settings2Icon,
  ArrowLeftRightIcon,
  TableOfContentsIcon,
  LetterTextIcon,
  TextCursorIcon,
  ToggleRightIcon,
  SquareStackIcon,
  RectangleEllipsisIcon,
} from 'lucide-react-native';

export const COMPONENTS = [
  { name: 'accordion', icon: ListCollapseIcon },
  { name: 'alert', icon: AlertCircleIcon },
  { name: 'alert-dialog', icon: AlertTriangleIcon },
  { name: 'aspect-ratio', icon: InspectionPanelIcon },
  { name: 'avatar', icon: CircleUserRoundIcon },
  { name: 'badge', icon: BadgeIcon },
  { name: 'button', icon: RectangleHorizontalIcon },
  { name: 'card', icon: IdCardIcon },
  { name: 'checkbox', icon: SquareCheckBigIcon },
  { name: 'collapsible', icon: FoldVerticalIcon },
  { name: 'context-menu', icon: PictureInPicture2Icon },
  { name: 'dialog', icon: CaptionsIcon },
  { name: 'dropdown-menu', icon: ChevronDownIcon },
  { name: 'hover-card', icon: MousePointer2Icon },
  { name: 'input', icon: TextCursorInputIcon },
  { name: 'label', icon: TagIcon },
  { name: 'menubar', icon: Rows3Icon },
  { name: 'popover', icon: SquaresIntersectIcon },
  { name: 'progress', icon: HourglassIcon },
  { name: 'radio-group', icon: ListIcon },
  { name: 'select', icon: ListCheckIcon },
  { name: 'separator', icon: MinusIcon },
  { name: 'skeleton', icon: BoneIcon },
  { name: 'switch', icon: ToggleRightIcon },
  { name: 'tabs', icon: TableOfContentsIcon },
  { name: 'text', icon: LetterTextIcon },
  { name: 'textarea', icon: TextCursorIcon },
  { name: 'toggle', icon: ArrowLeftRightIcon },
  { name: 'toggle-group', icon: SquareStackIcon },
  { name: 'tooltip', icon: RectangleEllipsisIcon },
];
